version: '3'

services:
  glpi-srv:
    build: .
    ports:
      - "127.0.0.1:18080:8080"
    depends_on:
      - glpi-db
    networks:
      - glpi-network

  glpi-db:
    image: mariadb:11.1
    environment:
      - MARIADB_USER=glpi-user
      - MARIADB_PASSWORD=glpi-password
      - MARIADB_ROOT_PASSWORD=root-password
      - MARIADB_DATABASE=glpi
    networks:
      - glpi-network

networks:
  glpi-network:
