version: '3'

services:
  glpi-db:
    image: mariadb:11.1
    env_file:
      - .env
    networks:
      - glpi-network

  glpi-srv:
    build:
      context: .
      args:
        GLPI_VERSION: 10.0.10
    ports:
      - "127.0.0.1:18080:8080"
    depends_on:
      - glpi-db
    networks:
      - glpi-network

networks:
  glpi-network:
